# Generated by Django 4.2.2 on 2023-06-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jbimage',
            name='job_images',
            field=models.URLField(max_length=1000),
        ),
    ]
